# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Theo Rogalski
user_description: Welcome to my website! I'm Theo, a computer engineering student interested in Artificial Intelligence/Machine Learning, Hardware Design and the cloud. My work experience includes making impactful software at an environmental agency and beign the lead software developer at my university's Makerspace.
user_title: Computer Engineering Student
email: rogalski.theo@gmailcom
twitter_username: lorem_ipsum
github_username:  theohrogalski
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
